baseURL = "/"
title = "AC Wilson"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  logo = "img/logo.png"
  logo_small = "img/logo-small.png"
  logo_text = "AC Wilson"
  disabled_logo = true
  about_us = "AC Wilson specializes in building scalable web applications, automating DevOps workflows, and empowering teams through modern software development practices. Focused on transparency and knowledge sharing to help businesses succeed."
  copyright = "Copyright (c) 2024, AC Wilson Dev LLC; all rights reserved."
  date_format = "January 2, 2006"
  viewMorePostLink = "/blog/"
  style = "custom"
  # Custom colors
  custom_css = ["css/custom.css"]
  font_families = [
    "Montserrat:400,700",
    "Merriweather:400,300italic,300"
  ]
  mainSections = ["blog"]
  
  # Contact form configuration
  formspree_action = "https://formspree.io/f/mvgkbyla"
  email = "aaron@acwilson.dev"

[params.testimonials]
  enable = false

[params.carouselHomepage]
  enable = true
  auto_play = true
  slide_speed = 2000  # 2 seconds per slide
  pagination_speed = 1000

[params.see_more]
  enable = true
  title = "Empowering Through Technology"
  subtitle = "Transparent. Approachable. Empowering."
  link_url = "/services"
  link_text = "Explore Our Services"

[params.features]
   enable = true
   cols = 4

[params.clients]
  enable = false

[params.recent_posts]
  enable = true
  title = "Latest Insights"
  subtitle = "Sharing knowledge and fostering open collaboration"

[params.widgets]
  search = true
  categories = true
  tags = true

[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "services"
  name = "Services"
  url = "/services"
  weight = 3

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 4

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url  = "/contact"
  weight = 5