baseURL = "/"
title = "AC Wilson"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  logo = "img/logo.png"
  logo_small = "img/logo-small.png"
  about_us = "AC Wilson exists to create technology and knowledge that empower..."
  copyright = "Copyright (c) 2024, AC Wilson; all rights reserved."
  date_format = "January 2, 2006"
  viewMorePostLink = "/blog/"
  style = "default"
  # Custom colors
  custom_css = ["css/custom.css"]
  font_families = [
    "Montserrat:400,700",
    "Merriweather:400,300italic,300"
  ]
  mainSections = ["blog"]
  
  # Contact form configuration
  formspree_action = "https://formspree.io/f/your-formspree-endpoint"
  email = "contact@example.com"
  address = """
    <strong>Your Company Name</strong>
    <br>123 Main Street
    <br>City, State 12345
    <br>Country
    """

[params.testimonials]
  enable = false

[params.see_more]
  enable = true
  title = "Empowering Through Technology"
  subtitle = "Transparent. Approachable. Empowering."
  link_url = "/services"
  link_text = "Explore Our Services"

[params.clients]
  enable = false

[params.recent_posts]
  enable = true
  title = "Latest Insights"
  subtitle = "Sharing knowledge and fostering open collaboration"

[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "services"
  name = "Services"
  url = "/services/"
  weight = 3

[[menu.main]]
  identifier = "web-services"
  name = "Web Services"
  url = "/services/web-services/"
  parent = "services"
  weight = 1

[[menu.main]]
  identifier = "cicd"
  name = "CI/CD"
  url = "/services/cicd/"
  parent = "services"
  weight = 2

[[menu.main]]
  identifier = "managed-services"
  name = "Managed Services"
  url = "/services/managed-services/"
  parent = "services"
  weight = 3

[[menu.main]]
  identifier = "ml-ai"
  name = "ML/AI"
  url = "/services/ml-ai/"
  parent = "services"
  weight = 4

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 4

[[menu.main]]
  identifier = "pricing"
  name = "Pricing"
  url = "/pricing/"
  weight = 5
